spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: contas-route
          uri: lb://MS-CONTAS
          predicates:
            - Path=/api/v1/contas/**

        - id: transacoes-route
          uri: lb://MS-TRANSACOES
          predicates:
            - Path=/api/v1/transacoes/**

        - id: investimentos-route
          uri: lb://MS-INVESTIMENTOS
          predicates:
            - Path=/api/v1/investimentos/**

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8080