spring:
  application:
    name: ms-transacoes
  datasource:
    url: jdbc:postgresql://postgres-transacoes:5432/transacoes
    username: postgres
    password: batman
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      binders:
        kafka-binder:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: kafka-transacoes:9092

        rabbitmq-binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq-transacoes
                port: 5672
                username: user
                password: password

      bindings:
        rendimentoInput-in-0:
          destination: financeiro.rendimentos
          binder: kafka-binder
          group: transacoes-rendimento-consumer-group

        alerta-vencido-out-0:
          destination: financeiro.alertas
          binder: rabbitmq-binder